name: Run api_test
on :
  [push]
        #paths:
          #- docker_volume\data\data_api.csv
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install httpx
        pip install fastapi
        pip install pytest
        pip install joblib
        pip install pandas
        pip install scipy

    - name: Run api_test
      run: |
        cd test_unitaires && pytest -v api_test.py