name: Run Tests


push:
    paths:
      - 'test_unitaires/kpi_movie_model/dict_prediction_comparaison.pkl'
      - 'test_unitaires/kpi_movie_model/dict_stability.pkl' # Note : Assurez-vous que le chemin est correct (test_unitaires ou test_unitaire ?)



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest numpy
    - name: Run tests model
      run: |
        cd test_unitaires
        pytest movie_model_test.py